{% set name = "flask-session" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Flask-Session-{{ version }}.tar.gz
  sha256: 0768e2bbf06f963ec1aa711bde7aa32dc39ff70f89b495d6db687d899eae4423

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - cachelib
    - flask >=0.8

test:
  imports:
    - flask_session
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fengsp/flask-session
  summary: Adds server-side session support to your Flask application
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
