{% set name = "flask-session" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flask_session-{{ version }}.tar.gz
  sha256: b1ed06cf4c5a211305579a132e81307d242cec6fe2714a276405730ffd22a034

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - flit-core <4
    - pip
  run:
    - python >=3.7
    - flask >=2.2
    - cachelib

test:
  imports:
    - flask_session
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pallets-eco/flask-session
  summary: Server-side session support for Flask
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - xylar
