{% set name = "flask-session" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Flask-Session-{{ version }}.tar.gz
  sha256: 190875e6aebf2953c6803d42379ef3b934bc209ef8ef006f97aecb08f5aaeb86

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - flit_core <4
    - pip
  run:
    - python >=3.7
    - flask >=2.2
    - cachelib

test:
  imports:
    - flask_session
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pallets-eco/flask-session
  summary: Server-side session support for Flask
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - xylar
